# Лабораторная работа №2

ФИО:  **Смирнов Александр Андреевич**   
Группа: **БИВТ-20-1**  

Отправлять можно следующими способами (**обязательно указать свое ФИО и группу в каком-либо виде**):
1. Создать **приватный** репозиторий на github, добавить меня по нику (l3lush) в Collaborators (Settings -> Collaborators -> Add people)
2. Отправить заполненный ноутбук мне на почту avmysh@gmail.com, либо m1603956@edu.misis.ru
3. Отправить заполненный ноутбук мне в тг @l3lush. 

**Deadlines**:
- soft -- **02.04.2023 23:59** (за сдачу в пределах этого времени +1 балл в табличку)
- hard -- **16.04.2023 23:59**


**Что необходимо сделать**:
1. Заполнить все ячейки ниже кодом так, чтобы прошли все `assert`ы.

# Задача 1. Реализовать слой с функцией активации "сигмоида"

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/1200px-Logistic-curve.svg.png)

Формула сигмоиды:
$$
f(x) = \frac {1}{1 + e^{-x}}
$$

In [1]:
import numpy as np

In [2]:
class SigmoidLayer():

    def __init__(self):
        """
        На будущее необходимо сохранить параметры и gradInput 
        """
        self.params = None
        self.gradInput = None
        
        pass

    def forward(self, X):
        """
        Реализовать forward pass
        P.S. не забудьте сохранить X во внутреннюю переменную
        """
        self.X = X

        return 1/(1+np.exp(-X))
        pass

In [3]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
#print(X)
sigmoid = SigmoidLayer()
output = sigmoid.forward(X)
correct_answer = np.array([[0.57313782, 0.62961995, 0.54773438],
                           [0.51696857, 0.68718368, 0.65843628],
                           [0.65419284, 0.64005501, 0.50976449],
                           [0.58851107, 0.7202462 , 0.51500666],
                           [0.70350447, 0.70626044, 0.51279562]])

assert np.isclose(output[:5], correct_answer).all()
assert hasattr(sigmoid, "params"), "Нет параметра params в реализованном классе"
assert hasattr(sigmoid, "gradInput"), "Нет параметра gradInput в реализованном классе"
assert hasattr(sigmoid, "X"), "Не сохранили X в реализованном классе"

# Задача 2. Реализовать слой с активацией гиперболического тангенса

![](https://production-media.paperswithcode.com/methods/Screen_Shot_2020-05-27_at_4.23.22_PM_dcuMBJl.png)

In [4]:
class TanhLayer():
    def __init__(self):
        """
        На будущее необходимо сохранить параметры и gradInput 
        """
        self.params = None
        self.gradInput = None
        
        pass
    

    def forward(self, X):
        """
        Реализовать forward pass
        P.S. не забудьте сохранить X во внутреннюю переменную
        """
        self.X = X.copy()

        return (np.exp(X)-np.exp(-X))/(np.exp(X)+np.exp(-X))
        pass

In [5]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
tanh = TanhLayer()
output = tanh.forward(X)
correct_answer = np.array([[0.28642281, 0.48582948, 0.18921297],
                           [0.0677962 , 0.65669792, 0.57591821],
                           [0.5632092 , 0.51946218, 0.03904306],
                           [0.34328675, 0.73782249, 0.05997262],
                           [0.69833441, 0.70505935, 0.05114899]])
assert np.isclose(output[:5], correct_answer).all()
assert hasattr(tanh, "params"), "Нет параметра params в реализованном классе"
assert hasattr(tanh, "gradInput"), "Нет параметра gradInput в реализованном классе"
assert hasattr(tanh, "X"), "Не сохранили X в реализованном классе"

# Задача 3. Реализовать функцию потерь MSE

В качестве интерактива-микрозадания, поищите формулу MSE в гугле 😊

In [6]:
class MSELoss():
    def forward(self, y_true, y_pred):
        """
        Реализовать forward pass
        """
        
        return ((y_true - y_pred)**2).sum() / y_pred.size
        pass

In [7]:
np.random.seed(17)

y_true = np.random.randint(0, 1000, size=(100))
y_pred = np.random.randint(0, 1000, size=(100))
mse = MSELoss()
output = mse.forward(y_true, y_pred)
print(output)
correct_answer = 157953.51
assert round(output) == round(correct_answer)

157953.51


# Задача 4. Реализовать каркас нейросети

In [8]:
class LinearLayer:
    """
    Линейный слой с семинаров, ничего менять не надо
    """
    def __init__(self, in_size, out_size):
        self.W = np.random.randn(in_size, out_size)
        self.params = [self.W]
        self.gradW = None
        self.gradInput = None
        
    def forward(self, X):
        self.X = X.copy()
        output = X.dot(self.W)
        print(self.W)
        return output


class NN:
    def __init__(self, loss_func):
        """
        Необходимо, чтобы нейросеть знала все о своей конфигурации.
        1. Создайте внутренние переменные layers, params и grads как пустые листы.
        2. Во внутреннюю переменную loss_func положите значение полученной переменной loss_func.
        """
        self.layers = []
        self.params = []
        self.grads = []
        self.loss_func = loss_func
        pass

    def add_layer(self, layer):
        """
        Функция добавления слоев в нейросеть.
        Необходимо, чтобы обновлялись (расширялись) внутренние переменные,
        ответственные за слои и параметры этих самых слоев, которые мы инициализировали
        в __init__ методе.
        """
        self.layers.append(layer)
        pass

    def forward(self, X):
        """
        Реализовать forward pass для всей нейросети.
        Т.е. реализовать forward pass по каждому слою, и в конце выдать результат 
        """
        for i in range (self.layers.__len__()):
             X = self.layers[i].forward(X)
        return X

In [9]:
nn = NN(MSELoss())

assert hasattr(nn, "layers")
assert hasattr(nn, "params")
assert hasattr(nn, "grads")
assert hasattr(nn, "loss_func")
assert isinstance(nn.loss_func, MSELoss)

In [10]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
nn = NN(MSELoss())

linear1 = LinearLayer(3, 5)
nn.add_layer(linear1)

sigmoid1 = SigmoidLayer()
nn.add_layer(sigmoid1)

linear2 = LinearLayer(5, 1)
nn.add_layer(linear2)

sigmoid2 = SigmoidLayer()
nn.add_layer(sigmoid2)

output_nn = nn.forward(X)

assert round(output_nn.sum()) == 65

[[ 0.33732948  0.26569806  0.99643045  1.25677661 -2.2161242 ]
 [-0.3287093   0.12151784  0.50575728 -0.522335   -0.59177353]
 [ 0.00829246  0.40167972  1.87760524 -0.54459678  0.37619153]]
[[-0.71117744]
 [ 1.95104048]
 [-0.75899181]
 [ 0.22927153]
 [ 1.40683388]]


# Задача 5. Соберите свою собственную нейросеть

Конфигурация сети, как на картинке
![](https://waksoft.susu.ru/wp-content/uploads/2021/05/nn-title.png)

Активации любые на ваш вкус (можете чередовать, делать одни и те же и прочее, что душе угодно)

In [11]:
np.random.seed(17)

nn = NN(MSELoss())
X = np.random.random(size=(100, 3))
print(X.shape)

linear1 = LinearLayer(4, 4)
nn.add_layer(linear1)

linear2 = LinearLayer(4, 5)
nn.add_layer(linear2)

linear3 = LinearLayer(5, 6)
nn.add_layer(linear3)

linear4 = LinearLayer(6, 4)
nn.add_layer(linear4)

linear5 = LinearLayer(4, 3)
nn.add_layer(linear5)

linear6 = LinearLayer(3, 3)
nn.add_layer(linear6)


(100, 3)


In [12]:
np.random.seed(17)
X = np.random.randn(100, 4)
output = nn.forward(X)

assert output.shape == (100, 3)

layer_weights = []
for layer in nn.layers:
    if isinstance(layer, LinearLayer):
        layer_weights.append(layer.W.shape)
right_weights = [(4, 4), (4, 5), (5, 6), (6, 4), (4, 3), (3, 3)]
assert layer_weights == right_weights

[[ 0.33732948  0.26569806  0.99643045  1.25677661]
 [-2.2161242  -0.3287093   0.12151784  0.50575728]
 [-0.522335   -0.59177353  0.00829246  0.40167972]
 [ 1.87760524 -0.54459678  0.37619153 -0.71117744]]
[[ 1.95104048 -0.75899181  0.22927153  1.40683388 -1.06941278]
 [-1.21943649  0.63515878 -0.63989946  1.60005952 -0.73053211]
 [-1.00961838 -1.00258633  0.0681837  -2.0945802   0.20400452]
 [ 0.38814262 -1.75707828 -0.4824393  -0.50772612  1.38866649]]
[[ 0.06055428 -0.04893002 -0.54879678  1.07547275  0.83341686 -1.47583658]
 [ 0.74712368  1.00258257  0.2258517   0.97527548  0.73848242 -1.53902354]
 [-0.61467094  0.20814807 -0.18790157 -0.86316959 -1.23754406 -1.29235042]
 [-1.99923375 -0.07382168 -0.27681805 -1.36027232  0.5855727  -0.97528801]
 [-1.64405171 -1.27124784 -1.05299662  0.2792999  -0.82506997  0.32110636]]
[[-0.11374406  1.35794504 -0.11545032 -0.76371361]
 [-2.75919108 -0.15617236  0.84418205 -0.0958334 ]
 [-0.04700253  0.27679941 -0.1259984   0.53984661]
 [-0.83124689

Если прошли все ассерты, поздравляю, теперь вы способны построить полносвязную сеть любой конфигурации для любой задачи 🥳️🥳️🥳️🥳️🥳️🥳️🥳️
![](https://kartinkof.club/uploads/posts/2022-06/1655926105_23-kartinkof-club-p-kartinki-s-nadpisyu-kto-molodets-ya-molode-24.jpg)